title: Yue Wang's Homepage
page-top-title: Yue Wang
top-section-bg-text: Homepage&ensp;|&ensp;个人主页
home-subtitle: Yue Wang&ensp;|&ensp;王岳
copyright-text: '&copy; Yue Wang 2024-2025. All Rights Reserved.'
